### ISSUE TITLE
Webhooks no longer work.

### ISSUE THREAD

**Issue by aebian** [scottbedard/oc-webhooks-plugin#3]
Hello Scott,

I got a weird issue with my Gitlab and your Webhooks plugin. 
For some reason if I commit to my repo, the main page doesn't get update anymore.
Alltough the application (gitlab) and the webhooks-plugin are telling me that the hook was successfully executed?!

Thats the Repo: https://sc.knight-industries.org/knight-industries-org/www-knight-industries-org
The Gitlab Webhook Setting: 

![Image](https://img.aebian.org/Webhooks_%C2%B7_Settings_%C2%B7_Knight_Industries__www-knig_2016-05-06_18-08-30.png)

And the Webhooks Setting in the OctoberCMS Backend: 

![Image](https://img.aebian.org/Update_Hook__Knight_Industries_-_Google_Chrome_2016-05-06_18-12-39.png)

The Git Project is set to trigger on build success. Then it should push the code to the page.
It worked before but I'm not sure whats wrong.

Log of the Webhook:

![Image](https://img.aebian.org/Webhooks_%C2%B7_Settings_%C2%B7_Knight_Industries__www-knig_2016-05-06_18-19-57.png)

And the newest logs are somehow empty :s

![image](https://img.aebian.org/Update_Hook__Knight_Industries_-_Google_Chrome_2016-05-06_18-23-18.png)

Do you have nay advice?

**Comment by scottbedard** [comment]
Hmm, I wonder what has changed that caused it to stop working. Did you modify the webhook script, or anything with the git repository? I haven't pushed any changes to the webhooks plugin in a while, when was the last time this hook was working?

**Comment by aebian** [comment]
Hmm about a week or so. Only thing I changed was the auth method form password to SHA-2 certificate.  But I don't think that this is the problem.
Last Day it worked was
![image](https://img.aebian.org/Update_Hook__Knight_Industries_-_Google_Chrome_2016-05-06_20-41-19.png)

And I didn't changed the Webhooks code.

**Comment by scottbedard** [comment]
Hmm, well since the last successful pull was about a week ago, and around that time was also when you changed the auth method, I'm willing to be that's your problem. Try setting it back to the way it was and see if that fixes it, then we'll know for sure.

**Comment by aebian** [comment]
Nope that didn't worked out. Even a newly created Webhook for a different project doesn't work.

**Comment by scottbedard** [comment]
Try changing the script to this and see if the hook is even triggering anything

```
echo "foo"
```

**Comment by aebian** [comment]
![image](https://img.aebian.org/Update_Hook__Knight_Industries_-_Google_Chrome_2016-05-06_22-45-25.png) Yes that worked

**Comment by scottbedard** [comment]
Ok so the webhook is definitely being hit, and it's executing the script. Something about the git pull must be causing the problem. I don't have time to try and recreate it right now, but I'm still inclined to believe it's some kind of authentication issue with GitLab.

**Comment by aebian** [comment]
Yes it was a permission issue. Had to change the key of my webuser to 700, issue therefore closed!

**Comment by scottbedard** [comment]
Sweet, glad you got it straightened out :)
