### ISSUE TITLE
Staging to Production

### ISSUE THREAD

**Issue by AugmentBLU** [scottbedard/oc-webhooks-plugin#4]
Hello,

If I have a staging server and wanted to update pages/content, then push changes to production, would this script be what I'm looking for?

I have October on a staging server, clients will want to control their content etc but I do not want them doing this on the live site. Once they're done, they can push the changes to the master branch using a `push to production` button?  

I have Bitbucket hooked up to Forge so that would trigger the deployment anyway for the last hurdle.

Thanks!

**Comment by scottbedard** [comment]
This plugin doesn't provide any functionality like that for you, it just gives you a way to connect shell scripts to webhooks. With that said, you should be able to write a script that does your deployment for you, and then wire it up to whatever event you want to trigger it,
